version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run:
          name: Build and publish Docker Image
          command: |
              export DOCKER_BUILDKIT=1
              TAG=v${CIRCLE_BUILD_NUM}
              IMAGE=liveauctioneers/hammer-ui
              docker login -u ${DOCKER_USER} -p ${DOCKER_PASS} 
              docker build -t ${IMAGE}:${TAG} . --progress plain
              echo ${CIRCLE_BUILD_NUM} > build_num.txt 
              wait
              docker push ${IMAGE}:${TAG}
              docker tag ${IMAGE}:${TAG} ${IMAGE}:${CIRCLE_BRANCH} && docker push ${IMAGE}:${CIRCLE_BRANCH}
    